# Generated by Django 3.2.16 on 2023-02-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_allow_empty_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='', max_length=13, verbose_name='ISBN'),
        ),
    ]
