# Generated by Django 3.2.16 on 2023-02-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13, verbose_name='ISBN'),
        ),
    ]
